i = input('Digite algo:')
print('O tipo primitivo é ', type(i))
print('So tem espaco?', i.isspace())
print('É um numero?', i.isnumeric())
print('É alfabetico?', i.isalpha())
print('É alfanumerico?', i.isalnum())
print('É tudo maiusculo?', i.isupper())
print('É tudo minisculo?', i.islower())
print('Esta capitalizada?', i.istitle())